name: Node CI Action
description: "Reusable Node.js build, lint, test, and artifact logic"

inputs:
  node-version:
    required: false
    default: "20"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: "npm"

    - name: Install dependencies
      run: npm ci
      shell: bash

    - name: Lint code
      run: npx eslint . || true
      shell: bash

    - name: Run tests
      run: npx vitest run --reporter=json --outputFile=test-results.json
      shell: bash

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: node-test-results
        path: test-results.json
