name: Go CI Action
description: "Reusable Go build, lint, test, and artifact logic"

inputs:
  go-version:
    required: false
    default: "1.22"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}
        cache-dependency-path: go.sum

    - name: Lint code
      run: go vet ./...
      shell: bash

    - name: Build
      run: go build ./...
      shell: bash

    - name: Run tests
      run: go test -v ./... -json > test-results.json
      shell: bash

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: go-test-results
        path: test-results.json

