name: First workflow

on:
  push

jobs:
  run shell commands:
    runs-on: ubuntu-latest
    steps:
      - name: print a command
        run: echo "Hello World!"
      - name: print multiline
        run: |
          node -v
          npm -v
          




  
    