name: Get Build Number

on:
  push:
    branches:
      - feat/test



jobs:
  get-build-number:
    runs-on: ubuntu-latest
    steps:
    - name: Output Run ID
      run: echo Run Id is ${{ github.run_id }}
    - name: Output Run Number
      run: echo Run number is ${{ github.run_number }}
    - name: Output Run Attempt
      run: echo Run Attempt is ${{ github.run_attempt }}