name: "Deployment Of Node Project"

on: 
  push:


jobs:
  Lint: 
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4.1.0

      - name: Install Dependencies
        run: npm ci

      - name: Lint test
        run: npm run lint

  Test:
    needs: Lint
    runs-on: ubuntu_latest
    steps:

      - name: Code checkout
        uses: actions/checkout@v4.1.0
        
      - name: Install Dependencies
        run: npm ci

      - name: Test
        run: npm run test

  Deploy:
    needs: [Lint,Test]
    runs-on: ubuntu-latest
    steps:

      - name: Code checkout
        uses: actions/checkout@v4.1.0
        
      - name: Install Dependencies
        run: npm ci


      - name: Build
        run: npm run build

      - name: Deploy
        run: echo "Deploying ............"
