name: Release Tag

on:
  # push:
  #   branches:
  #     - main

permissions:
  contents: write
  pull-requests: read


jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          tag_prefix: "v"
          

      - name: Check Output Parameters

        run: |
          echo "Got tag name ${{ steps.release.outputs.tag_name }}"
          echo "Got release version ${{ steps.release.outputs.version }}"
          echo "Upload release artifacts to ${{ steps.release.outputs.upload_url }}"
          echo "Its a test modification nothing new "
          ### adding a line but not staging it
          echo " adding a line "
          