name: Release Workflow

on:
  workflow_dispatch:
  push:
    # tags:
    #   - 'v*'
    branches:
      - main


permissions:
  contents: write
  pull-requests: read

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build package
        run: |
          npm install
          npm pack

      # - name: Archive Site Content
      #   uses: thedoctor0/zip-release@main
      #   with: 
      #     filename: site.zip

      - name: Create ZIP archive
        run: |
          mkdir -p release
          zip -r release/release.zip . -x 'node_modules/*' -x '.git/*' -x 'release/*' -x 'tests/*' 
          
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          # GITHUB_TOKEN: ${{ secrets.SERVICE_PAT }} 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use the PAT_TOKEN secret
        with:
          tag_name: "v1.0.${{ github.run_number }}"
          release_name: "Release v1.0.${{ github.run_number }}"
          body: |
            This is the release of my Node.js project version Release v1.0.${{ github.run_number }}.

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          # GITHUB_TOKEN: ${{ secrets.SERVICE_PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/release.zip # Update with correct file path
          asset_name: site-v${{ github.run_number }}    # Update with correct file name
          asset_content_type: application/zip


    



